#!/bin/sh

SYSROOT=${BASE_DIR}/sysroot

export PKG_CONFIG_PATH=
export PKG_CONFIG_SYSROOT_DIR=${SYSROOT}
export PKG_CONFIG_LIBDIR=\
${SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:\
${SYSROOT}/usr/share/pkgconfig:\
${SYSROOT}/usr/lib/pkgconfig

exec pkg-config "$@"
